export default Object.freeze({
  SET_CHILDREN: 'fileTree.SET_CHILDREN',
  COLLAPSE_FOLDER: 'fileTree.COLLAPSE_FOLDER',
  START_RENAME: 'fileTree.START_RENAME',
  START_ADD_FOLDER: 'fileTree.START_ADD_FOLDER',
  START_ADD_FILE: 'fileTree.START_ADD_FILE',
  CONTINUE_RENAME: 'fileTree.CONTINUE_RENAME',
  STOP_RENAME: 'fileTree.STOP_RENAME',

  TOGGLE_FOLDER: 'fileTree.TOGGLE_FOLDER',
  REFRESH_FOLDER: 'fileTree.REFRESH_FOLDER',
  IMPORT_FILES: 'fileTree.IMPORT_FILES',
  COMMIT_RENAME: 'fileTree.COMMIT_RENAME'
})
