export default Object.freeze({
  SWITCH_PAGE: 'landingPages.SWITCH_PAGE',
  SET_TEMPLATES: 'landingPages.SET_TEMPLATES',
  SET_NEW_PROJECT_NAME: 'landingPages.SET_NEW_PROJECT_NAME',
  SET_NEW_PROJECT_PATH: 'landingPages.SET_NEW_PROJECT_PATH',
  SET_NEW_PROJECT_TEMPLATE: 'landingPages.SET_NEW_PROJECT_TEMPLATE',
  SET_ERROR: 'landingPages.SET_ERROR',

  FIND_TEMPLATES: 'landingPages.FIND_TEMPLATES',
  PICK_NEW_PROJECT_LOCATION: 'landingPages.PICK_NEW_PROJECT_LOCATION',
  CREATE_PROJECT: 'landingPages.CREATE_PROJECT',
  OPEN_PROJECT: 'landingPages.OPEN_PROJECT'
})
